# Use a base image
FROM node:16.13

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files
# COPY ./server ./server
COPY . .

# Expose the port on which the Express server will run
EXPOSE 3333