# Use the official PostgreSQL as the base image
FROM timescale/timescaledb:latest-pg13

# Copy the initialization script to the container
COPY data.sql /docker-entrypoint-initdb.d/

# Set environment variables for TimescaleDB configuration
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD mysecretpassword
ENV POSTGRES_DB kafka_sonar_db