{
 "title": "Kafka  Broker / Performance & Latency",
 "tags": [
  "kafka",
  "broker",
  "troubleshoot"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Envrionment",
    "query": "label_values(kafka_server_brokerstate, env)"
   },
   {
    "name": "instance",
    "label": "Broker Host",
    "query": "label_values(kafka_network_request_metrics_time_ms{env=\"$env\"}, instance)"
   },
   {
    "name": "request",
    "label": "Request Type",
    "query": "label_values(kafka_network_request_metrics_time_ms, request)"
   }
  ]
 },
 "panels": [
  {
   "title": "Request Total Time Ms (All Fetch)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_network_request_metrics_time_ms{request=~\"Fetch\", aggregate=~\"Mean\", scope=~\"Total\",env=\"$env\"}",
     "legendFormat": "{{instance}} / {{ aggregate}}"
    }
   ]
  },
  {
   "title": "Request Total Time Ms (Fetch - Consumer)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_network_request_metrics_time_ms{request=~\"FetchConsumer\", aggregate=~\"Mean\", scope=~\"Total\",env=\"$env\"}",
     "legendFormat": "{{instance}} / {{ aggregate}}"
    }
   ]
  },
  {
   "title": "Request Total Time Ms (Fetch - Follower)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_network_request_metrics_time_ms{request=~\"FetchFollower\", aggregate=~\"Mean\", scope=~\"Total\",env=\"$env\"}",
     "legendFormat": "{{instance}} / {{ aggregate}}"
    }
   ]
  },
  {
   "title": "Request Total Time Ms (Produce)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "kafka_network_request_metrics_time_ms{request=~\"Produce\", aggregate=~\"Mean\", scope=~\"Total\",env=\"$env\"}",
     "legendFormat": "{{instance}} / {{ aggregate}}"
    }
   ]
  }
 ]
}